server:
  port: 8080
  context-path: /LeaveWord
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.44.196:3306/leaveword?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
