server:
  port: 8080
  context-path: /LeaveWord
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///leaveword?characterEncoding=utf8&useSSL=false
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
